export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
